### ISSUE TITLE
IE11 Error using property created inside bind()

### ISSUE THREAD

**Issue by fabioluz** [aurelia/binding#362] opened 2016-03-26 07:57 UTC
IE11 and Edge throw an error when using a property created inside the `bind()` method. 

For instance:
```
ViewModel.js
bind() {
  this.test = 'asdad';
}

View.html
<a id.bind="test"></a>
```

This works on Chrome and FF, but doesn't work on IE11 and Edge

Thanks!

**Comment by jdanyow** [comment] 2016-03-26 18:18
@fabioluz I can't reproduce this using the code you provided- here's what I see in IE11:
![ie11](http://i.imgur.com/MNMRpna.png)

And edge:
![edge](http://i.imgur.com/oJC4KuY.png)

**Comment by fabioluz** [comment] 2016-03-26 19:43
Sorry @jdanyow I put the wrong tag in the example. The problem happens when I bind the `colspan` attribute of a `td`. For example:

```
<template>
  <table>
    <tr>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td colspan.bind="test"></td>
    </tr>
  </table>
</template>
```

```
export class Welcome {
  bind() {
    this.test = 2;
  }
}
```

![error aurelia](https://cloud.githubusercontent.com/assets/5049361/14062095/cfa2a8e8-f371-11e5-9be0-6233564341d2.png)


If I declare `test` outside of `bind()` it works normally.

**Comment by jdanyow** [comment] 2016-03-26 22:56
ah ok- IE is fussy about what is programmatically assigned to colspan.  Make sure the property is defined and positive prior to the bind method being called.

https://github.com/aurelia/binding/issues/343

**Closed by jdanyow** 2016-03-26 22:56 UTC
Labels: question
