### ISSUE TITLE
Change to a bound repeat input element is applied to the VM a second time after the element has been deleted.

### ISSUE THREAD

**Issue by geleto** [aurelia/binding#527] opened 2016-10-20 16:44 UTC
**I'm submitting a bug report**

* **Library Version:**
1.0.7

* **Browser:**
Chrome

I have an array of strings bound to a repeat with input text elements. I want to delete an element when  the user deletes it's content. Because there is no way to observe changes in array values, I handle the `input` event, check for empty values and remove the corresponding elements from the array.

The **bug** is - the bound value (which was just changed to empty text by the user) is applied to the VM twice, the first time after the input content has been deleted by the user, and once again - after the element is deleted from the array in the event handler, which blanks the next element which has taken it's place. I tried to avoid this **bug** by using queueTask to postpone deleting the array element, to no avail.

See this gist, to reproduce the **bug**, just delete the text in one of the first 3 inputs:
https://gist.run/?id=e49828b236d979450ce54f0006d0fa0a

**Comment by geleto** [comment] 2016-10-21 16:36
This is not a question, it's a bug report. Sorry to ask how to work around the bug in the P.S. - I have removed it.

**Comment by jdanyow** [comment] 2016-10-22 19:01
@geleto I'm closing this because it's a duplicate of https://github.com/aurelia/binding/issues/444

Please refer to the discussion in that issue for more information. The short answer is this doesn't do anything in pure javascript:

```js
for (let item of items) {
  item = 'something else'; // note: this does not change the contents of the array
}
```

Similarly, this doesn't do anything in a `repeat.for` either:

```html
<input repeat.for="item of items"
       value.bind="item">  // note : this does not change the contents of the array
```

**Closed by jdanyow** 2016-10-22 19:01 UTC
Labels: question

**Comment by geleto** [comment] 2016-10-22 21:35
I do the binding correctly, and the bound array is changed - no problem here. Problem is after I delete an array element, the same change is wrongly applied a second time, but to a different element which has taken the place of the deleted one.
<template>
  <div repeat.for="i of messages.length">
    <input type="text" value.bind="$parent.messages[i]" input.delegate="onMessageChanged()">
  </div>
</template>

**Comment by geleto** [comment] 2016-10-23 05:07
I have created a simpler test case in this gist:
https://gist.run/?id=f3e7002bf3b60472313b8f9c5963c7c4

When any value is changed, the first element in the array is deleted. Notice how the new value is duplicated.
