### ISSUE TITLE
model binded to "null" is always converted to empty object

### ISSUE THREAD

**Issue by yd290276** [aurelia/binding#283] opened 2016-01-10 06:47 UTC
When a model bind to a null value, aurelia.binding always convert null (or undefined) to an empty object.
This has for effect to change the binded value in aurelia core and then trigger again (twice) the change handler for the property in the VM.

Code exemple in a view with a select element :
```html
<select
                            ref="select_area"
                            class="form-control"
                            id="select_template_zone"
                            value.bind="imagecropperVM.currentArea"
                            disabled.bind="!templateSelected">
                        <option model.bind="null" selected>Select a zone...</option>
                        <option repeat.for="[id,zone] of templatezones.zones" model.bind="id" value="${id}">${zone.name}</option>
                    </select>
```

In this example, when first select option is selected, then a first call to change handler is done with a new value of "null", then automatically a second call is done with the new value sets to "Object" because in aurelia-bindings.js, line 1426, the code checks if "instance" is wether null or undefined and if so, it changes the value to an empty object "{}".

I think this behavior/feature is not what developpers/users expect, so aurelia should handle correctly null or undefined value for bindings instead changing the value.

**Comment by jdanyow** [comment] 2016-01-10 07:26
agree, duplicate of https://github.com/aurelia/binding/issues/205

**Closed by jdanyow** 2016-01-10 07:26 UTC
