### ISSUE TITLE
View goes out of sync with model on select list options change

### ISSUE THREAD

**Issue by istrau3** [aurelia/binding#382] opened 2016-04-19 17:37 UTC
Please see the following reproduction:
https://gist.run/?id=d933d929a37ec4bf4d0a1ffc89a8b586

Note that initially 'bob' whose value is 1 is selected. The model (this.selected) is also equal to 1 (as seen after the button). After the "Modify Options" button is clicked, 'joe', whose value is 2, is selected but the model is still equal to 1. The model and view have gone out of sync.

I don't think the view and the model should ever go out of sync. It seems in this case, after the options are switched out, the select list is maintaining its internal selectedIndex (and consequently switching the selected value that is displayed) but the aurelia model is not syncing to the new selected value.

Ideally Aurelia would ensure that its model was persisted through the switch. So, in this case, if I had bob selected and then I switched the options, bob would still be selected but there would be other options to choose from (if bob was not available in the new list then the first options would be selected just like a new select list).

That said, I think if the select list's new selected value was bound up into the model after the options change that would still be a lot better than the current situation. Taking the above case again, if joe's value (2) was bound into the model after the options were switched out and the select list selected him (because it is maintaining the selectedIndex of 1), then I could replicate the ideal mechanism by manually reselecting bob (I would have to put some unecessary logic in my view model 
```javascript
let originalValue = this.selected;
this.options = newOptions;
this.taskQueue.queueTask(() => this.selected = originalValue);
````
). 

With the current situation, even if I try something like the code above, it does nothing because selected already equals originalValue, it is out of sync with the view.

**Comment by jdanyow** [comment] 2016-04-23 12:35
The option element's value attribute coerces everything to a string. This breaks your use-case because your ids are numbers.  Use [`model.bind`](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.2/doc/article/cheat-sheet/5) instead: https://gist.run/?id=2a593616215e62873df2389d27aa80cc

**Comment by istrau3** [comment] 2016-04-25 20:04
@jdanyow Thanks for the response (and the tip to use the model.bind instead of value.bind). That said, the gist you linked to does not solve the problem. In fact, it further underlines the problem. In your gist, the model and value go out of sync as well when the options are switched out. 

1) viewModel.selected = 2, select displays 'joe' whose value is 2
2) click modify options 
3) viewModel.selected still = 2, select displays 'bob' whose value is 1

the model and view are out of sync by which I mean that the view is incorrectly rendering the model. 

Like I said in my original post, I believe this is a result of the select list maintaining its internal selectedIndex through the options modification. In other words, after the modify options button is clicked, the select list maintains a selectedIndex of 2 (which now points to bob whose value is 1) while the Aurelia model (viewModel.selected) is still 2.

**Comment by jdanyow** [comment] 2016-07-10 17:26
I think this is fixed by https://github.com/aurelia/templating-binding/commit/5d772caf4af5b3ba835526cc01f48b9e44c7d8d0

Will re-test the gist when the release goes out on tuesday.

Potentially impacted by https://github.com/aurelia/binding/commit/9d39a1adee1175e44d20634593a297ba5cdc674a as well

**Comment by jdanyow** [comment] 2016-07-23 11:52
confirmed this is working now https://gist.run/?id=2a593616215e62873df2389d27aa80cc

**Closed by jdanyow** 2016-07-23 11:52 UTC
Labels: bug

**Comment by istrau3** [comment] 2016-07-25 16:55
@jdanyow 
I just checked the gist. Doesn't seem to be working to me. 

In other words, at first joe (whose value is 1) is selected and vm.selected === 2. After clicking "modify options", vm.selected === 2 but "bob" is selected (in the dropdown) whose value is 1. The view and model are out of sync.

**Comment by jdanyow** [comment] 2016-07-25 18:20
whose gist are you using? I'm talking about this one:  https://gist.run/?id=2a593616215e62873df2389d27aa80cc

**Comment by istrau3** [comment] 2016-07-25 18:55
@jdanyow yes, that one. If you click "modify options" the dropdown shows "bob" but vm.selected === 2 (bob's value !== 2).

**Comment by shawty** [comment] 2017-04-10 20:10
I can confirm this, as Iv'e just tested, while looking for an answer to a similar issue myself.

**Comment by Eagle94T** [comment] 2017-06-28 06:40
I can also confirm, changing the select field also changes the select-id, but modify the select field with the `modify options` button, didn't change the select-id

**Comment by istrau3** [comment] 2017-06-28 19:12
@jdanyow I think this should probably still be open.
