### ISSUE TITLE
Intercept Binding Behavior Misbehaving

### ISSUE THREAD

**Issue by gregoryagu** [aurelia/binding#693] opened 2018-06-03 19:53 UTC
**I'm submitting a bug report**

* **Library Version:**
171

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **JSPM OR Webpack AND Version**
webpack 3.5

* **Browser:**
all
* **Language:**
TypeScript

**Current behavior:**
When using Intercept Binding Behavior, `this` is not set properly.

I am using the Intercept Binding Behavior as shown in the Docs.

    const interceptMethods = ['updateTarget', 'updateSource', 'callSource'];

    export class InterceptBindingBehavior {
      bind(binding, scope, interceptor) {
        let i = interceptMethods.length;
        while (i--) {
          let method = interceptMethods[i];
          if (!binding[method]) {
            continue;
          }
          binding[`intercepted-${method}`] = binding[method];
          let update = binding[method].bind(binding);
          binding[method] = interceptor.bind(binding, method, update);
        }
      }

      unbind(binding, scope) {
        let i = interceptMethods.length;
        while (i--) {
          let method = interceptMethods[i];
          if (!binding[method]) {
            continue;
          }
          binding[method] = binding[`intercepted-${method}`];
          binding[`intercepted-${method}`] = null;
        }
      }
    }

     <template>
      <require from="./intercept-binding-behavior"></require>

      <div mousemove.delegate="mouseMove($event) & intercept:myFunc"></div>

      <input value.bind="foo & intercept:myFunc">
    </template>`

Then, when myFunc runs, this does not refer to the viewmodel, but to the binding.

     myFunc() {
		this.DoSomething();  //DoSomething is not found.
     }

**Expected/desired behavior:**
this is set to the correct object

**Comment by StrahilKazlachev** [comment] 2018-06-03 20:16
Only a some binding commands *preserve* the *this*. 
Also try to rework the behavior, how it uses the *interceptor*, since currently it is working as expected.
> `binding[method] = interceptor.bind(binding, method, update);`

Or I'm missing your point.

**Comment by StrahilKazlachev** [comment] 2018-06-03 20:40
This is how I understood this issue:
I pass a function and want when called to have its *this* pointing to the VM(**not** the InterceptBindingBehavior) it originated from and not the binding itself.
But in the binding behavior it is being bound to have its *this* point to the binding - `binding` being the first argument.
> `binding[method] = interceptor.bind(binding, method, update);`

You could make that function an arrow function in the VM and later bind only the arguments, and if the binding itself is needed bind it as an argument also.

**Comment by Alexander-Taran** [comment] 2018-06-13 16:46
@gregoryagu 
`myFunc = () =>{ this.DoSomething();  }`

**Comment by EisenbergEffect** [comment] 2018-06-19 03:21
Closing since the behavior is working as designed and we have a solution recommendation.

**Closed by EisenbergEffect** 2018-06-19 03:21 UTC
