### ISSUE TITLE
Binding to files of input type=file in firefox fails to update on change

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia/binding#314] opened 2016-02-09 22:33 UTC
Following this article: http://www.danyow.net/binding-to-file-inputs-with-aurelia/ I linked a model property to file and showing the images with the help of value converter from the same article.

Everything works great on first files selection. chrome/ff/ie all show the images.
But **if i decide to select files again - firefox does not update the images**. Although change event fires ok. 
I'm using change.trigger to grab the actual contents of files as described in another arcitle 
http://www.petermorlion.com/file-upload-with-aurelia/

**Comment by jdanyow** [comment] 2016-02-22 01:02
[I can reproduce this](https://gist.run/?id=51db953515fb1cac0b07)

**Comment by genericuser-me** [comment] 2016-06-08 15:29
I am using chrome. I resolved it in following manner, please let me know if this is OK:

View:
<input type="file" change.delegate="onFileUploadChange()"
                                    name="files[]" ref="filepdf" files.bind="selectedFiles"
                                    accept=".pdf,.zip" multiple
                                    style="opacity:0; cursor: pointer; width: 45px; height: 10px;"
                                     size="0" alt="Upload">

ViewModel:

   filepdf: HTMLInputElement;

onFileUploadChange(e) {
//after processing
 this.filepdf.value = "";
}

**Comment by elefantino** [comment] 2016-06-13 12:32
genericuser-me, there is no such a bug in Chrome. This issue exists in Firefox. Your solution does not help

**Comment by elefantino** [comment] 2016-06-13 13:14
as a solution, you can use change.delegate="yourFunction($event)" in the file input, and add transforming of FileList to Array in this function in the view-model.
Code example:
View-model
```
selectedFilesArray;
onSelectFile(e)
  {
    if (this.selectedFiles) {
      this.selectedFilesArray = [];
      for(let i = 0; i < this.selectedFiles.length; i++) {
        this.selectedFilesArray.push(this.selectedFiles.item(i));
      }
    }
  }
```
View
```
<input type="file" multiple accept="image/*" files.bind="selectedFiles" change.delegate="onSelectFile($event)">
  <ul>
    <li repeat.for="file of selectedFilesArray">
      <h1>${file.name}: ${file.type} ${file.size / 1000} kb</h1>
      <img src.bind="file | blobToUrl"><img>
      Last Modified: ${file.lastModifiedDate}
    </li>
  </ul>
```

**Comment by EisenbergEffect** [comment] 2016-07-04 14:30
@jdanyow Can you provide a status on this?

**Comment by jdanyow** [comment] 2016-07-05 12:57
I can reproduce, haven't worked on a fix yet.  Issue needs to remain open.

**Comment by Alexander-Taran** [comment] 2016-07-21 20:16
Also for this bucket:  
`form>input[type=file]+button[type=reset] `
now clicking reset button clears the form, but the same binding as in original post does not see the change.

**Comment by rajsibi7** [comment] 2016-10-12 16:31
How to save the file in server?

**Comment by abemeister** [comment] 2017-01-04 02:52
I found a solution for Firefox and also maintain the file list if selecting images from a different directory
**elefantino** was pointing in the right direction by using the change.delegate

It's true Firefox does loose the file bindings when re-select but can maintain it through the **change.delegate** binding instead of the **files.bind**. 

This code in Typescript:

**View Model:**

    private galleryFiles: File[] = [];

    private galleryFilesMap: Map<string, File> = new Map<string, File>();

    private getGalleryFiles(): File[] {
        let galleryFiles: File[] = [];

        this.galleryFilesMap.forEach((file: File, name: string) => {
            galleryFiles.push(file);
        });

        return galleryFiles;
    }

    public updateFilesSelect(event: Event) {
        let updatedFiles: File[] = event.target['files'];

        for (let index = 0; index < updatedFiles.length; index++) {
            let updateFile: File = updatedFiles[index];

            let fileName: string = updateFile.name;

            this.galleryFilesMap.set(fileName, updateFile);
        }

        // Refer to galleyFiles object in the repeater to control your gallery list and main the file selects from different folders 
        this.galleryFiles = this.getGalleryFiles();
	}

**View:**
            
            <input type="file"
                   multiple
                   accept="image/*"
                   change.delegate="updateFilesSelect($event)">

            <div repeat.for="file of galleryFiles" class="thumbnail gallery-item">
                

                
                    <h4>${file.name}: ${file.type}</h4>
                    <p class="mt-1">Last Modified: ${file.lastModifiedDate}</p>
              </div>

**Comment by apollocoder** [comment] 2018-01-04 14:32
This is still an issue. Is there a fix in sight?

**Comment by michaelwoodew** [comment] 2018-04-06 13:43
Also causing issue with me too

**Comment by Alexander-Taran** [comment] 2018-04-06 13:50
the workaround is in the same article.. I mentioned.. you just don't use binding to file
you process the change event and as an outcome - you create your value

think of it as binding to files is not possible
work with change event

**Comment by michaelwoodew** [comment] 2018-04-06 15:50
I just added a `ref="fileinput"` to the input then used `this.fileinput.value = null`
That way, next time i select a file it forces the .value to change and triggers the change event

**Comment by fkleuver** [comment] 2018-05-29 13:14
I had a quick look at this. The binding isn't actually "lost" on re-select; rather, it's never created in the first place. In Firefox a lot of things seem to happen quite differently on initial page load. I'll look into this more.

**Comment by Alexander-Taran** [comment] 2018-05-29 14:00
@fkleuver there is no real need.. actually.. you still have to observe the change to get the content of the files..

**Comment by fkleuver** [comment] 2018-05-29 14:41
@Alexander-Taran Well this issue was still open so I took that as an indicator that this still needed fixing. And from what I see it still looks like a bug. It has behavior A in Chrome and behavior B in Firefox. That's not right either way.

**Comment by Alexander-Taran** [comment] 2018-06-01 17:21
@fkleuver 
(-: I could close it.. but for consistency..
There are known bugs that are not getting fixed ever..

**Comment by fkleuver** [comment] 2018-08-12 11:36
Having gone completely through the element observers as well as the relevant parts of the spec, it looks like this can be solved properly. There was also a bugfix related to this in FF a few months ago. Will definitely be fixed in vNext

**Closed** 2019-01-07 10:09 UTC
Labels: bug
