### ISSUE TITLE
OoObjectObserver callbacks null

### ISSUE THREAD

**Issue by flieks** [aurelia/binding#173] opened 2015-09-30 11:49 UTC
it's difficult to reproduce but i'm getting an error at:
```
OoObjectObserver.prototype.unsubscribe = function unsubscribe(propertyName, callback) {
      var callbacks = this.callbacks[propertyName],
```
where this.callbacks is null.

stacktrace:
unsubscribe (aurelia-binding.js:3403)
updateRight (aurelia-binding.js:822)
(anonymous function) (aurelia-binding.js:809)
notify (aurelia-binding.js:847)
(anonymous function) (aurelia-binding.js:830)
call (aurelia-binding.js:3220)
check (aurelia-binding.js:3176)
(anonymous function) (aurelia-binding.js:3164)

this happens after an input value which is binded to a vm value which became null (through breeze revert())

**Comment by jdanyow** [comment] 2015-09-30 12:13
this is fixed in the upcoming release.  There's a workaround here:

https://github.com/aurelia/binding/issues/150

**Closed by jdanyow** 2015-09-30 12:13 UTC
Labels: duplicate

**Comment by flieks** [comment] 2015-09-30 12:35
@jdanyow hi, i did copy your workaround from that issue correctly but still getting the same error:
`Uncaught TypeError: Cannot read property 'indexOf' of null` at unsubscribe

**Comment by jdanyow** [comment] 2015-09-30 14:17
ok- apologies- it will be fixed in the upcoming release.  

Go ahead and add a `if (callbacks === null) return;` as a temporary work-around.

**Comment by shanonvl** [comment] 2015-09-30 20:00
@jdanyow, same issue here.  After removing the original workaround, then adding null check per your recommendation ( snippet below ), the issue is resolved on my end. Thanks! 
```javascript
OoObjectObserver.prototype.unsubscribe = function unsubscribe(propertyName, callback) {
      var callbacks = this.callbacks[propertyName],
          index = callbacks ? callbacks.indexOf(callback) : -1;
      if (index === -1) {
        return;
      }
```

**Comment by flieks** [comment] 2015-10-01 10:37
yes that fixed it:
i puted it like this
```
 OoObjectObserver.prototype.unsubscribe = function unsubscribe(propertyName, callback) {      
         if (this.callbacks === null) return;
         
      var callbacks = this.callbacks[propertyName],
          index = callbacks.indexOf(callback);
```
