### ISSUE TITLE
Support for Set collection

### ISSUE THREAD

**Issue by sgurenkov** [aurelia/binding#157] opened 2015-08-26 23:54 UTC
There are a bindings for Maps and Arrays. Is there any plans to add support for Sets collection?

**Comment by jdanyow** [comment] 2015-09-18 19:00
@EisenbergEffect / @martingust what do you think?

**Comment by jdanyow** [comment] 2015-09-18 19:26
closing- this is a dupe of https://github.com/aurelia/templating-binding/issues/34

**Closed** 2015-09-18 19:26 UTC
Labels: enhancement, question
