### ISSUE TITLE
Binding input value to a property of nullable

### ISSUE THREAD

**Issue by grlscz** [aurelia/binding#117] opened 2015-06-18 22:59 UTC
Consider the following view:

```html
<div id="list">
  <ul>
    <li repeat.for="item of items">
      <a href="#" click.trigger="$parent.select(item)">${item.name}</a>
    </li>
    <li>
      <a href="#" click.trigger="select(null)"><i>unselect</i></a>
    </li>
  </ul>
</div>
<div id="selection" if.bind="selectedItem">
  <h3>value.one-way</h3>
  <input type="text" value.one-way="selectedItem.name" />
</div>
<!--div id="selection2" if.bind="selectedItem">
  <h3>value.bind</h3>
  <input type="text" value.bind="selectedItem.name" />
</div-->
```

With one-way binding this works as expected: if we click "unselect" setting `selectedItem` to `null`, selection div is hidden. However if we uncomment the "selection2" part with two-way `value.bind`, upon unselecting neither of two "selection" divs disappears. No errors thrown in the console.

Demo: http://plnkr.co/edit/vbiYJmRjGL4K9r8r3ctG?p=preview

**Comment by jdanyow** [comment] 2015-06-24 13:27
Tracked this down, I don't know if this is a bug or an unsupported scenario.

First I set a breakpoint in the `if` behavior.  When "unselect" is clicked, the divs are removed as expected.  Immediately afterwards, the breakpoint is hit again and the value is `{ name: '' }`.  In other words, after setting `selectedItem` to null it somehow became `{ name: '' }`.  The call stack didn't show why due to the micro-task queuing so I changed your `selectedItem` property to a getter/setter style property:

```javascript
  _selectedItem = null;
  get selectedItem() {
    return this._selectedItem;
  }
  set selectedItem(newValue) {
    this._selectedItem = newValue;
  }
```

After setting a breakpoint in the property setter I could see the empty object was coming from here:

https://github.com/aurelia/binding/blob/master/src/ast.js#L241

`AccessMember` is creating an object on the fly in situations where the binding expression is attempting to assign a property of a null/undefined object value.

Another part of the problem is the value binding:  `value.bind="selectedItem.name"`.  This is a `PathExpression` and when `selectedItem` is assigned null, the entire expression evaluates to `null` which then gets assigned to the input's value property which only accepts strings, so the value becomes empty string (`""`).

cc @EisenbergEffect

**Comment by grlscz** [comment] 2015-06-24 13:40
Thank you. It could be by design - this behaviour might be useful. It still doesn't seem intuitive to me - i'd expect binding to not change `selectedItem` in any case, and either throw an error or silently do nothing as in the case of one-way - it ignores the member access of null-valued `selectedItem`.

**Closed** 2015-10-26 15:15 UTC
Labels: question

**Comment by danfma** [comment] 2015-10-28 20:03
Well, I understand the mechanism of the bindings and what is happing but I can't agree that this should be the default behavior.
