### ISSUE TITLE
Binding using class not working in aurelia docs getting started example custom element nav-bar

### ISSUE THREAD

**Issue by delebash** [aurelia/binding#381] opened 2016-04-19 07:56 UTC
Windows 7 x64
aurelia-framework: "^1.0.0-beta.1.1.3"
modified webpack skeleton navigation  -- just changed some html in the template

In the Getting Started docs -- Creating Custom Element section 
creating the nav-bar binding you can either use 

` <template bindable="router"> `

or javascript class

```
import {bindable} from 'aurelia-framework';

export class NavBar {
  @bindable router = null;
}
```

The javascript class version does not seem to be working.  The ` <template bindable="router"> ` works fine. I was able to create the secret-message using the js class version from the Templating: Custom Element section and that worked as expected.

```
export class SecretMessageCustomElement {
  secretMessage = 'Be sure to drink your Ovaltine!';
}

```

**Comment by EisenbergEffect** [comment] 2016-04-19 13:26
@AshleyGrant Can you take look at the docs. They may need some clarification. I'm closing this since I know there's not a bug.

**Closed by EisenbergEffect** 2016-04-19 13:26 UTC

**Comment by delebash** [comment] 2016-04-20 14:23
@AshleyGrant 
It was a difference of removing the .html in` <require from="./nav-bar"></require> `when using `<template>` verse having the .html ` <require from="./nav-bar.html"></require> ` when using `<template bindable="router">`

[answered ]( http://stackoverflow.com/questions/34148851/aurelia-nav-bar-vm-not-working)on stackoverflow

Would be nice to make this distinction in the docs clearer
